name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f4d7c2b3e2e6e2e2e2e2e2e2e2e2e2e2e2e2e2e2
      - name: Set up JDK 17
        uses: actions/setup-java@c9b4b6e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@b1e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io